name: Sync Fork with Upstream

on:

  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4  # Using the latest version

    - name: Add upstream remote
      run: git remote add upstream https://github.com/KelvinTegelaar/cipp.git

    - name: Fetch all branches from upstream
      run: git fetch upstream

    - name: Set up Git user
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Check for changes and merge
      run: |
        git diff --quiet upstream/main || git merge upstream/main --allow-unrelated-histories

    - name: Push changes to fork
      run: git push origin main
