name: Update Fork

on:
  schedule:
    - cron: '0 0 * * *' # This runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v2
        with:
          ref: main # Change to your default branch

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream repository
        run: git remote add upstream https://github.com/KelvinTegelaar/CIPP
        # Change original-username/original-repo to the upstream repo

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main # Change to your default branch
          git merge upstream/main # Change to the upstream branch you want to merge

      - name: Push changes
        run: git push origin main # Change to your default branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
